# Generated by Django 4.0.5 on 2022-06-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='itemID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactform',
            name='contact',
            field=models.CharField(max_length=11),
        ),
    ]
