# Generated by Django 4.0.5 on 2022-06-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_contactform_itemid_alter_contactform_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='itemID',
        ),
    ]
