# Generated by Django 4.0.5 on 2022-06-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_login_contactform_password_contactform_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='contactform',
            name='salary',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='firstname',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='lastname',
            field=models.CharField(max_length=45),
        ),
    ]
