# Generated by Django 4.0.5 on 2022-07-05 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_person_contactform_salary_alter_contactform_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_key', models.IntegerField()),
                ('updated_field', models.CharField(max_length=2000)),
                ('updated_value', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='address',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, 'must contain atleast 10 characters')]),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='contact',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'only positive 11 digits are allowed')]),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='firstname',
            field=models.CharField(max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'only alphabets are allowed')]),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='lastname',
            field=models.CharField(max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'only alphabets are allowed')]),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='salary',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator('^[0-9]+$', 'only numbers are allowed')]),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='username',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]([._-](?![._-])|[a-zA-Z0-9]){3,18}[a-zA-Z0-9]$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]([._-](?![._-])|[a-zA-Z0-9]){3,18}[a-zA-Z0-9]$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
